In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2082, 1486, 8368, 4464],
 [2082, 1486, 8368, 3256],
 [2082, 3051, 8368, 4585],
 [1903, 763, 168, 9007, 2748],
 [1903, 763, 168, 9007, 9809],
 [8033, 2082, 3230, 8368, 3123],
 [503, 4189, 8400, 9007]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2082 1486 8368 4464]
 [   0    0    0    0 2082 1486 8368 3256]
 [   0    0    0    0 2082 3051 8368 4585]
 [   0    0    0 1903  763  168 9007 2748]
 [   0    0    0 1903  763  168 9007 9809]
 [   0    0    0 8033 2082 3230 8368 3123]
 [   0    0    0    0  503 4189 8400 9007]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 469ms/step


array([[[ 0.01362172,  0.03795225,  0.00949895,  0.02891398,
         -0.04310697, -0.00888669, -0.04898261,  0.00878905,
         -0.01062978, -0.04418707],
        [ 0.01362172,  0.03795225,  0.00949895,  0.02891398,
         -0.04310697, -0.00888669, -0.04898261,  0.00878905,
         -0.01062978, -0.04418707],
        [ 0.01362172,  0.03795225,  0.00949895,  0.02891398,
         -0.04310697, -0.00888669, -0.04898261,  0.00878905,
         -0.01062978, -0.04418707],
        [ 0.01362172,  0.03795225,  0.00949895,  0.02891398,
         -0.04310697, -0.00888669, -0.04898261,  0.00878905,
         -0.01062978, -0.04418707],
        [-0.01704634,  0.03131285, -0.00480724, -0.03189114,
         -0.02060028, -0.00922317, -0.03748853,  0.03945078,
          0.03845043, -0.04176186],
        [-0.02239699, -0.02048539, -0.0378534 ,  0.02214492,
          0.02324902,  0.00685352,  0.02443326, -0.00147585,
         -0.01731152, -0.0246399 ],
        [-0.02981354,  0.04488568,  0.00710833, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2082, 1486, 8368, 4464])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 75ms/step


array([[ 0.01362172,  0.03795225,  0.00949895,  0.02891398, -0.04310697,
        -0.00888669, -0.04898261,  0.00878905, -0.01062978, -0.04418707],
       [ 0.01362172,  0.03795225,  0.00949895,  0.02891398, -0.04310697,
        -0.00888669, -0.04898261,  0.00878905, -0.01062978, -0.04418707],
       [ 0.01362172,  0.03795225,  0.00949895,  0.02891398, -0.04310697,
        -0.00888669, -0.04898261,  0.00878905, -0.01062978, -0.04418707],
       [ 0.01362172,  0.03795225,  0.00949895,  0.02891398, -0.04310697,
        -0.00888669, -0.04898261,  0.00878905, -0.01062978, -0.04418707],
       [-0.01704634,  0.03131285, -0.00480724, -0.03189114, -0.02060028,
        -0.00922317, -0.03748853,  0.03945078,  0.03845043, -0.04176186],
       [-0.02239699, -0.02048539, -0.0378534 ,  0.02214492,  0.02324902,
         0.00685352,  0.02443326, -0.00147585, -0.01731152, -0.0246399 ],
       [-0.02981354,  0.04488568,  0.00710833, -0.02690833, -0.01476578,
         0.04288102,  0.00020527, -0.00772994